import type { Email, InboxSummary } from "../types";

const now = Date.now();
const h = (hoursAgo: number) => new Date(now - hoursAgo * 3600_000).toISOString();

export const MOCK_EMAILS: Email[] = [
  {
    id: "e1",
    from: "Nubank",
    fromEmail: "noreply@nubank.com.br",
    subject: "Sua fatura de novembro está disponível",
    preview: "Olá, sua fatura no valor de R$ 1.284,90 vence em 12/11. Acesse o app para ver os detalhes.",
    body: "Olá,\n\nSua fatura do mês de novembro está disponível.\nValor: R$ 1.284,90\nVencimento: 12/11/2026\n\nAcesse o app Nubank para visualizar a fatura completa e realizar o pagamento.\n\nAtenciosamente,\nEquipe Nubank",
    time: h(0.5),
    folder: "inbox",
    risk: "trusted",
    riskScore: 4,
    aiReason: "Domínio verificado (nubank.com.br), DKIM válido, padrão de comunicação consistente com o remetente legítimo.",
    unread: true,
  },
  {
    id: "e2",
    from: "GitHub",
    fromEmail: "noreply@github.com",
    subject: "[mailguard-ai] PR #42 aguarda sua revisão",
    preview: "rogerio-souza solicitou sua revisão no pull request #42: feat(api): integrar Gmail OAuth flow.",
    body: "rogerio-souza solicitou sua revisão em:\n\nfeat(api): integrar Gmail OAuth flow (#42)\n\nArquivos alterados: 12\nAdicionados: +432  Removidos: -87\n\nRevise no GitHub.",
    time: h(1.2),
    folder: "inbox",
    risk: "trusted",
    riskScore: 2,
    aiReason: "Remetente recorrente, headers íntegros, conteúdo consistente com notificações automáticas do GitHub.",
    unread: true,
  },
  {
    id: "e3",
    from: "RH | Ulife",
    fromEmail: "rh@ulife.com.br",
    subject: "Confirmação de entrevista — Quinta, 14h",
    preview: "Olá Caio, confirmamos sua entrevista técnica para quinta-feira às 14h. Link da call em anexo.",
    body: "Olá Caio,\n\nConfirmamos sua entrevista técnica:\n• Data: Quinta, 13/11\n• Horário: 14h00\n• Formato: Google Meet\n\nQualquer imprevisto, basta responder este email.\n\nAbraços,\nEquipe Ulife",
    time: h(3),
    folder: "inbox",
    risk: "trusted",
    riskScore: 8,
    aiReason: "Domínio corporativo confiável, sem links suspeitos, contexto coerente com histórico do usuário.",
  },
  {
    id: "e4",
    from: "Linear",
    fromEmail: "notifications@linear.app",
    subject: "Resumo semanal: 12 issues concluídas",
    preview: "Sua semana em números: 12 concluídas, 5 em progresso, 3 bloqueadas. Veja o relatório completo.",
    body: "Resumo da semana — MailGuard AI\n\n✓ 12 concluídas\n→ 5 em progresso\n⚠ 3 bloqueadas\n\nAcesse Linear para o detalhamento.",
    time: h(6),
    folder: "inbox",
    risk: "trusted",
    riskScore: 3,
    aiReason: "Notificação automática verificada, sem indícios de manipulação.",
  },
  {
    id: "e5",
    from: "Banco Itaú",
    fromEmail: "atendimento@itau-seguranca-online.net",
    subject: "URGENTE: Sua conta será bloqueada em 24h",
    preview: "Detectamos atividade suspeita. Clique aqui para revalidar seus dados imediatamente ou sua conta será bloqueada.",
    body: "Prezado cliente,\n\nDetectamos atividade SUSPEITA em sua conta. Para evitar o BLOQUEIO PERMANENTE em 24 horas, clique no link abaixo e revalide seus dados:\n\nhttp://itau-seguranca-online.net/revalidar?u=xz9\n\nNão ignore este email.\n\nDepartamento de Segurança Itaú",
    time: h(2),
    folder: "spam",
    risk: "dangerous",
    riskScore: 96,
    aiReason: "Domínio falso (itau-seguranca-online.net não pertence ao Itaú), tom de urgência artificial, link encurtado para coleta de credenciais. Padrão clássico de phishing bancário.",
    unread: true,
  },
  {
    id: "e6",
    from: "PROMOÇÃO IMPERDÍVEL",
    fromEmail: "ofertas@megapromo-brasil.click",
    subject: "🔥 iPhone 15 por R$ 199 — APENAS HOJE",
    preview: "Você foi selecionado! Garanta seu iPhone 15 por apenas R$ 199. Estoque limitado, clique já!",
    body: "PARABÉNS!!! Você foi um dos 10 selecionados para comprar um iPhone 15 por APENAS R$ 199,00!!!\n\nCLIQUE AQUI AGORA: http://megapromo-brasil.click/iphone\n\nOferta válida só hoje!",
    time: h(4),
    folder: "spam",
    risk: "dangerous",
    riskScore: 92,
    aiReason: "Promoção irrealista, domínio recém-registrado (.click), uso excessivo de caps lock e urgência. Indicadores fortes de scam.",
  },
  {
    id: "e7",
    from: "Newsletter Tech",
    fromEmail: "weekly@techbrasil.io",
    subject: "5 ferramentas de IA que você precisa testar",
    preview: "Curadoria semanal: as melhores ferramentas de IA lançadas esta semana, com reviews honestos.",
    body: "Olá dev,\n\nSelecionamos 5 ferramentas de IA que estão bombando:\n1. Claude Code\n2. Cursor\n3. v0 by Vercel\n4. Lovable\n5. Bolt\n\nLeia os reviews completos no site.",
    time: h(8),
    folder: "inbox",
    risk: "trusted",
    riskScore: 6,
    aiReason: "Newsletter com histórico de envio consistente, opt-in confirmado.",
  },
  {
    id: "e8",
    from: "Suporte Microsoft",
    fromEmail: "support@microsft-account.com",
    subject: "Verificação de conta necessária",
    preview: "Detectamos um login incomum em sua conta. Verifique sua identidade para continuar usando os serviços.",
    body: "Detectamos um login incomum:\nLocal: Lagos, Nigéria\nDispositivo: Windows 7\n\nSe não foi você, verifique sua identidade aqui: http://microsft-account.com/verify\n\nMicrosoft Support Team",
    time: h(5),
    folder: "spam",
    risk: "dangerous",
    riskScore: 94,
    aiReason: "Typo-squatting do domínio (microsft em vez de microsoft), engenharia social baseada em medo, URL fora do escopo oficial.",
  },
  {
    id: "e9",
    from: "Carla Mendes",
    fromEmail: "carla.mendes@empresa.com",
    subject: "Re: Proposta comercial — revisão final",
    preview: "Caio, segue a versão revisada com os ajustes que combinamos na call. Pode me dizer se ficou OK?",
    body: "Oi Caio,\n\nSegue a versão revisada da proposta com os ajustes que combinamos:\n• Escopo de integração ampliado\n• Prazo: 6 semanas\n• Valor atualizado\n\nMe diz se está OK pra eu enviar pro cliente.\n\nAbs,\nCarla",
    time: h(10),
    folder: "inbox",
    risk: "trusted",
    riskScore: 5,
    aiReason: "Conversa contínua com remetente conhecido, sem anexos suspeitos.",
  },
  {
    id: "e10",
    from: "Booking",
    fromEmail: "noreply@booking-confirmar.org",
    subject: "Sua reserva precisa de confirmação adicional",
    preview: "Sua reserva #87432 está pendente. Confirme seu cartão de crédito para evitar o cancelamento.",
    body: "Sua reserva #87432 está pendente.\n\nPara evitar cancelamento, confirme os dados do seu cartão:\nhttp://booking-confirmar.org/pay\n\nBooking Team",
    time: h(7),
    folder: "spam",
    risk: "dangerous",
    riskScore: 89,
    aiReason: "Domínio impersonando Booking.com, formulário externo solicitando dados de cartão. Padrão de fraude em e-commerce.",
  },
  {
    id: "e11",
    from: "Spotify",
    fromEmail: "no-reply@spotify.com",
    subject: "Sua wrapped chegou cedo este ano",
    preview: "2026 foi seu ano mais musical: 47.382 minutos ouvidos. Veja sua retrospectiva.",
    body: "Olha o que rolou no seu 2026:\n\n47.382 minutos\n412 artistas\nGênero #1: Lo-fi Hip Hop\n\nVeja a wrapped completa no app.",
    time: h(14),
    folder: "inbox",
    risk: "trusted",
    riskScore: 1,
    aiReason: "E-mail transacional verificado, SPF/DKIM/DMARC válidos.",
  },
  {
    id: "e12",
    from: "Receita Federal",
    fromEmail: "atendimento@receitafederal-gov.com",
    subject: "Sua restituição de IR está disponível",
    preview: "Você tem R$ 3.421,00 a receber. Cadastre sua chave PIX no link abaixo para receber em 24h.",
    body: "Prezado contribuinte,\n\nVocê tem R$ 3.421,00 de restituição disponível.\n\nCadastre sua chave PIX agora:\nhttp://receitafederal-gov.com/pix\n\nReceita Federal",
    time: h(9),
    folder: "spam",
    risk: "dangerous",
    riskScore: 97,
    aiReason: "Domínio falso (gov real é gov.br), Receita Federal nunca solicita PIX por email. Golpe extremamente comum no Brasil.",
    unread: true,
  },
  {
    id: "e13",
    from: "Vercel",
    fromEmail: "notify@vercel.com",
    subject: "Deploy concluído: mailguard-ai",
    preview: "Seu deploy foi publicado com sucesso. Build em 23s, sem warnings.",
    body: "Deploy concluído ✓\n\nProjeto: mailguard-ai\nBuild: 23s\nURL: https://mailguard-ai.vercel.app\n\nVer logs no dashboard.",
    time: h(11),
    folder: "inbox",
    risk: "trusted",
    riskScore: 2,
    aiReason: "Notificação automática de serviço autenticado.",
  },
  {
    id: "e14",
    from: "Mercado Livre",
    fromEmail: "envios@mercadolivre.com.br",
    subject: "Seu pedido foi enviado",
    preview: "Seu pedido #4892-MX já saiu para entrega. Previsão: 14/11.",
    body: "Olá,\n\nSeu pedido #4892-MX foi enviado.\nPrevisão de entrega: 14/11\nRastreio: ML9847234BR\n\nMercado Livre",
    time: h(16),
    folder: "inbox",
    risk: "trusted",
    riskScore: 4,
    aiReason: "Histórico de transação real associado ao remetente.",
  },
  {
    id: "e15",
    from: "Premiação SUSPEITA",
    fromEmail: "premio@vc-ganhou.xyz",
    subject: "Você ganhou R$ 50.000 — retire agora",
    preview: "Parabéns! Você foi sorteado. Pague apenas a taxa de R$ 49,90 para liberar seu prêmio.",
    body: "PARABÉNS! Você foi o sorteado da semana! Prêmio: R$ 50.000,00\n\nPague apenas a taxa administrativa de R$ 49,90 via PIX:\nchave: 11.222.333/0001-44\n\nApós pagamento envie comprovante.",
    time: h(13),
    folder: "spam",
    risk: "dangerous",
    riskScore: 99,
    aiReason: "Golpe de taxa antecipada (advance-fee fraud). Ninguém precisa pagar para receber prêmio legítimo.",
  },
  {
    id: "e16",
    from: "Notion",
    fromEmail: "team@notion.so",
    subject: "3 pessoas comentaram em 'Roadmap Q1'",
    preview: "Carla, Pedro e mais 1 deixaram comentários no documento. Veja as menções.",
    body: "Atividade no workspace MailGuard:\n• Carla comentou em 'Roadmap Q1'\n• Pedro respondeu sua menção\n• Ana adicionou checklist\n\nAbra no Notion.",
    time: h(18),
    folder: "inbox",
    risk: "trusted",
    riskScore: 3,
    aiReason: "Plataforma autenticada, padrão típico de notificação colaborativa.",
  },
  {
    id: "e17",
    from: "Curso Online",
    fromEmail: "contato@aprendaja-agora.site",
    subject: "Última chance: -90% no curso de Python",
    preview: "Apenas hoje, garanta acesso vitalício por R$ 17. Vagas limitadas.",
    body: "OFERTA RELÂMPAGO!\n\nCurso completo de Python por APENAS R$ 17 (de R$ 997)\n\nAcesso vitalício, certificado, mentoria.\n\nGaranta: http://aprendaja-agora.site/python",
    time: h(20),
    folder: "spam",
    risk: "suspicious",
    riskScore: 68,
    aiReason: "Domínio recém-registrado (.site), preço artificial, sem opt-in identificado. Provável spam comercial agressivo, não necessariamente phishing.",
  },
  {
    id: "e18",
    from: "Stripe",
    fromEmail: "support@stripe.com",
    subject: "Recibo de pagamento — R$ 89,00",
    preview: "Recibo do seu pagamento de R$ 89,00 para Lovable. Cartão final 4242.",
    body: "Recibo de pagamento\n\nValor: R$ 89,00\nDescrição: Lovable Pro — mensal\nCartão: •••• 4242\nData: hoje\n\nObrigado.",
    time: h(22),
    folder: "inbox",
    risk: "trusted",
    riskScore: 2,
    aiReason: "Recibo de transação real verificada via webhook do provedor.",
  },
];

export function buildSummary(emails: Email[]): InboxSummary {
  const todays = emails;
  const spam = emails.filter((e) => e.folder === "spam").length;
  const suspicious = emails.filter((e) => e.risk === "suspicious").length;
  const risky = emails.filter((e) => e.riskScore >= 50).length;
  const riskRate = Math.round((risky / Math.max(emails.length, 1)) * 100);
  return {
    analyzedToday: todays.length,
    spamDetected: spam,
    suspicious,
    riskRate,
  };
}
